language: objective-c
osx_image: xcode10.1
xcode_workspace: SwiftSDK.xcworkspace
xcode_scheme: SwiftSDK
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone Xs Max

before_install:
  - gem install cocoapods --pre
  - pod install --repo-update