language: objective-c
osx_image: xcode12.2
xcode_workspace: SwiftSDK.xcworkspace
xcode_scheme: SwiftSDK
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPhone 12 Pro Max

notifications:
  slack:
    rooms:
      - backendless:H83v3dKWMcg6F0OWDjFbwYRh#ios_github

before_install:
  - gem install cocoapods --pre
  - pod install --repo-update
